---
title: "uq"
author: "Kar"
date: '2022-07-21'
output: html_document
---

```{r}

income.type <- c("Commonwealth Grant Scheme grants", 
                 "Consultancy and contract revenue",
                 "FEE-HELP and course fees & charges", 
                 "HECS-HELP and HECS-HELP student payments", 
                 "Investment revenue", 
                 "Other government revenue", 
                 "Other revenue",
                 "Research block grants")

values <- c(339659,
            189168,
            699240,
            198244,
            217123,
            289649,
            164117,
            287800)

uq_rev <- data.frame(income.type, values) %>% 
  mutate(income.type = factor(income.type),
         total = sum(values),
         per = round(values/total*100)
         ) 

```

```{r, fig.height=8, fig.width=8}

pie(x = uq_rev$values,
    labels = uq_rev$income.type,
    col = c("red", "orange", "yellow", "green", "blue", "pink", "purple", "grey"),
    radius = 0.55)


```

```{r, fig.width=8, fig.height=8}

ggplot(uq_rev, aes(x = "", y = values, fill = values)) +
  geom_bar(stat = "identity", color = "black") +
  coord_polar(theta = "y", start = 0) +
  theme_minimal() +
   theme(legend.position = "NA",
         axis.title = element_blank(),
         axis.text = element_blank(),
         strip.text = element_text(size = 15), 
         plot.title = element_text(hjust = 0.5, face = "bold", vjust = 2),
         plot.subtitle = element_text(hjust = 0.5, vjust = 2)) +
  geom_label(aes(label = paste0(per, "%", "\n", 
                               "(", prettyNum(values, big.mark = ","), ")")),
            color = "black", fill = "white",
            position = position_stack(vjust = 0.5), size = 4) +
  scale_fill_gradient() +
  scale_y_continuous(breaks = uq_rev$values, labels = uq_rev$income.type)
  
```

```{r}
uq_rev <- uq_rev %>% 
  mutate(per = paste0(per, "%"))
```

```{r, fig.width=12, fig.height=6}
library(treemapify)

ggplot(uq_rev, aes(fill = -values, area = values)) +
  geom_treemap() +
  geom_treemap_text(aes(label = paste0(income.type, "\n", per, "\n",
                                  prettyNum(values, big.mark = ","))),
                    place = "center", color = "white") +
  theme(legend.position = "none",
        strip.background = element_rect(fill = "white"),
        plot.title = element_text(size = 20, face = "bold", vjust = 2, hjust = 0.5),
        strip.text = element_text(size = 15, face = "bold"))


```

## uq Attrition rate




